/* Generated By:JavaCC: Do not edit this line. TextDataParserTreeConstants.java Version 4.2 */
package org.apache.pig.data.parser;

public interface TextDataParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTBAG = 1;
  public int JJTTUPLE = 2;
  public int JJTMAP = 3;
  public int JJTKEYVALUEPAIR = 4;
  public int JJTATOMDATUM = 5;
  public int JJTDATUM = 6;


  public String[] jjtNodeName = {
    "Parse",
    "Bag",
    "Tuple",
    "Map",
    "KeyValuePair",
    "AtomDatum",
    "Datum",
  };
}
/* JavaCC - OriginalChecksum=40da785f595166630ee722b4637e1071 (do not edit this line) */
