/* Generated By:JJTree&JavaCC: Do not edit this line. TextDataParserConstants.java */
package org.apache.pig.data.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TextDataParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FLOATINGPOINT = 1;
  /** RegularExpression Id. */
  int DIGIT = 2;
  /** RegularExpression Id. */
  int INTEGER = 3;
  /** RegularExpression Id. */
  int SIGNEDINTEGER = 4;
  /** RegularExpression Id. */
  int LONGINTEGER = 5;
  /** RegularExpression Id. */
  int DOUBLENUMBER = 6;
  /** RegularExpression Id. */
  int FLOATNUMBER = 7;
  /** RegularExpression Id. */
  int NULL = 8;
  /** RegularExpression Id. */
  int STRING = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<FLOATINGPOINT>",
    "<DIGIT>",
    "<INTEGER>",
    "<SIGNEDINTEGER>",
    "<LONGINTEGER>",
    "<DOUBLENUMBER>",
    "<FLOATNUMBER>",
    "\"null\"",
    "<STRING>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
  };

}
