/* Generated By:JavaCC: Do not edit this line. PigFileParserConstants.java */
package org.apache.pig.tools.parameters;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PigFileParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int SPECIALCHAR = 7;
  /** RegularExpression Id. */
  int DECLARE = 8;
  /** RegularExpression Id. */
  int PIGDEFAULT = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int LITERAL = 11;
  /** RegularExpression Id. */
  int SHELLCMD = 12;
  /** RegularExpression Id. */
  int OTHER = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIALCHAR>",
    "\"%declare\"",
    "\"%default\"",
    "<IDENTIFIER>",
    "<LITERAL>",
    "<SHELLCMD>",
    "<OTHER>",
  };

}
