/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 4.2 */
package org.apache.pig.impl.logicalLayer.parser;

public interface QueryParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTSPLITCLAUSE = 1;
  public int JJTEXPR = 2;
  public int JJTNESTEDEXPR = 3;
  public int JJTIDENTIFIERORRESERVED = 4;
  public int JJTALIAS = 5;
  public int JJTBASEEXPR = 6;
  public int JJTLOADCLAUSE = 7;
  public int JJTSTRINGLIST = 8;
  public int JJTFILENAME = 9;
  public int JJTFILTERCLAUSE = 10;
  public int JJTSAMPLECLAUSE = 11;
  public int JJTLIMITCLAUSE = 12;
  public int JJTPCOND = 13;
  public int JJTPORCOND = 14;
  public int JJTPANDCOND = 15;
  public int JJTPUNARYCOND = 16;
  public int JJTPNOTCOND = 17;
  public int JJTPNULLCOND = 18;
  public int JJTCOGROUPCLAUSE = 19;
  public int JJTGROUPITEM = 20;
  public int JJTORDERCLAUSE = 21;
  public int JJTSORTCOL = 22;
  public int JJTCOLNAMEORNUM = 23;
  public int JJTCROSSCLAUSE = 24;
  public int JJTJOINCLAUSE = 25;
  public int JJTUNIONCLAUSE = 26;
  public int JJTFOREACHCLAUSE = 27;
  public int JJTSTREAMCLAUSE = 28;
  public int JJTCOMMAND = 29;
  public int JJTDEFINECLAUSE = 30;
  public int JJTPATHLIST = 31;
  public int JJTINPUTOUTPUTSPEC = 32;
  public int JJTCOMMANDSTREAM = 33;
  public int JJTERRORSPEC = 34;
  public int JJTSTORECLAUSE = 35;
  public int JJTNESTEDBLOCK = 36;
  public int JJTNESTEDCOMMAND = 37;
  public int JJTNESTEDPROJECT = 38;
  public int JJTNESTEDFILTER = 39;
  public int JJTNESTEDSORTORARRANGE = 40;
  public int JJTNESTEDDISTINCT = 41;
  public int JJTNESTEDLIMIT = 42;
  public int JJTGENERATESTATEMENT = 43;
  public int JJTFLATTENEDGENERATEITEMLIST = 44;
  public int JJTFLATTENEDGENERATEITEM = 45;
  public int JJTINFIXEXPR = 46;
  public int JJTADDITIVEEXPR = 47;
  public int JJTMULTIPLICATIVEEXPR = 48;
  public int JJTCASTEXPR = 49;
  public int JJTUNARYEXPR = 50;
  public int JJTNEGATIVEEXPR = 51;
  public int JJTBASEEVALSPEC = 52;
  public int JJTBINCOND = 53;
  public int JJTEVALFUNCSPEC = 54;
  public int JJTNONEVALFUNCSPEC = 55;
  public int JJTEVALARGS = 56;
  public int JJTEVALARGSITEM = 57;
  public int JJTTYPE = 58;
  public int JJTCOMPOSITETYPE = 59;
  public int JJTBASICTYPE = 60;
  public int JJTFIELDSCHEMA = 61;
  public int JJTATOMSCHEMA = 62;
  public int JJTSCHEMAMAP = 63;
  public int JJTSCHEMATUPLE = 64;
  public int JJTSCHEMABAG = 65;
  public int JJTTUPLESCHEMA = 66;
  public int JJTTYPEFIELDSCHEMA = 67;
  public int JJTTYPEATOMSCHEMA = 68;
  public int JJTTYPESCHEMAMAP = 69;
  public int JJTTYPESCHEMATUPLE = 70;
  public int JJTTYPESCHEMABAG = 71;
  public int JJTTYPETUPLESCHEMA = 72;
  public int JJTEVALFUNCTION = 73;
  public int JJTVOID = 74;
  public int JJTBRACKETEDSIMPLEPROJ = 75;
  public int JJTSIMPLEPROJ = 76;
  public int JJTBAG = 77;
  public int JJTTUPLE = 78;
  public int JJTMAP = 79;
  public int JJTKEYVALUEPAIR = 80;
  public int JJTATOMDATUM = 81;
  public int JJTDATUM = 82;
  public int JJTCONST = 83;
  public int JJTCOLORSPEC = 84;
  public int JJTDOLLARVAR = 85;
  public int JJTALIASFIELDORSPEC = 86;


  public String[] jjtNodeName = {
    "Parse",
    "SplitClause",
    "Expr",
    "NestedExpr",
    "IdentifierOrReserved",
    "Alias",
    "BaseExpr",
    "LoadClause",
    "StringList",
    "FileName",
    "FilterClause",
    "SampleClause",
    "LimitClause",
    "PCond",
    "POrCond",
    "PAndCond",
    "PUnaryCond",
    "PNotCond",
    "PNullCond",
    "CogroupClause",
    "GroupItem",
    "OrderClause",
    "SortCol",
    "ColNameOrNum",
    "CrossClause",
    "JoinClause",
    "UnionClause",
    "ForEachClause",
    "StreamClause",
    "Command",
    "DefineClause",
    "PathList",
    "InputOutputSpec",
    "CommandStream",
    "ErrorSpec",
    "StoreClause",
    "NestedBlock",
    "NestedCommand",
    "NestedProject",
    "NestedFilter",
    "NestedSortOrArrange",
    "NestedDistinct",
    "NestedLimit",
    "GenerateStatement",
    "FlattenedGenerateItemList",
    "FlattenedGenerateItem",
    "InfixExpr",
    "AdditiveExpr",
    "MultiplicativeExpr",
    "CastExpr",
    "UnaryExpr",
    "NegativeExpr",
    "BaseEvalSpec",
    "BinCond",
    "EvalFuncSpec",
    "NonEvalFuncSpec",
    "EvalArgs",
    "EvalArgsItem",
    "Type",
    "CompositeType",
    "BasicType",
    "FieldSchema",
    "AtomSchema",
    "SchemaMap",
    "SchemaTuple",
    "SchemaBag",
    "TupleSchema",
    "TypeFieldSchema",
    "TypeAtomSchema",
    "TypeSchemaMap",
    "TypeSchemaTuple",
    "TypeSchemaBag",
    "TypeTupleSchema",
    "EvalFunction",
    "void",
    "BracketedSimpleProj",
    "SimpleProj",
    "Bag",
    "Tuple",
    "Map",
    "KeyValuePair",
    "AtomDatum",
    "Datum",
    "Const",
    "ColOrSpec",
    "DollarVar",
    "AliasFieldOrSpec",
  };
}
/* JavaCC - OriginalChecksum=c9259a65ba06e1dfb7ceeff7d7354747 (do not edit this line) */
