/* Generated By:JavaCC: Do not edit this line. PigScriptParserConstants.java */
package org.apache.pig.tools.pigscript.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PigScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CAT = 6;
  /** RegularExpression Id. */
  int CD = 7;
  /** RegularExpression Id. */
  int COPY = 8;
  /** RegularExpression Id. */
  int COPYFROMLOCAL = 9;
  /** RegularExpression Id. */
  int COPYTOLOCAL = 10;
  /** RegularExpression Id. */
  int DUMP = 11;
  /** RegularExpression Id. */
  int DESCRIBE = 12;
  /** RegularExpression Id. */
  int ALIASES = 13;
  /** RegularExpression Id. */
  int EXPLAIN = 14;
  /** RegularExpression Id. */
  int HELP = 15;
  /** RegularExpression Id. */
  int KILL = 16;
  /** RegularExpression Id. */
  int LS = 17;
  /** RegularExpression Id. */
  int MOVE = 18;
  /** RegularExpression Id. */
  int MKDIR = 19;
  /** RegularExpression Id. */
  int PWD = 20;
  /** RegularExpression Id. */
  int QUIT = 21;
  /** RegularExpression Id. */
  int REGISTER = 22;
  /** RegularExpression Id. */
  int REMOVE = 23;
  /** RegularExpression Id. */
  int REMOVEFORCE = 24;
  /** RegularExpression Id. */
  int SET = 25;
  /** RegularExpression Id. */
  int ILLUSTRATE = 26;
  /** RegularExpression Id. */
  int RUN = 27;
  /** RegularExpression Id. */
  int EXEC = 28;
  /** RegularExpression Id. */
  int PARAM = 29;
  /** RegularExpression Id. */
  int PARAM_FILE = 30;
  /** RegularExpression Id. */
  int SCRIPT = 31;
  /** RegularExpression Id. */
  int DOT = 32;
  /** RegularExpression Id. */
  int OUT = 33;
  /** RegularExpression Id. */
  int BRIEF = 34;
  /** RegularExpression Id. */
  int SCRIPT_DONE = 35;
  /** RegularExpression Id. */
  int PIG = 91;
  /** RegularExpression Id. */
  int EOL = 92;
  /** RegularExpression Id. */
  int QUOTE = 93;
  /** RegularExpression Id. */
  int SEMICOLON = 94;
  /** RegularExpression Id. */
  int LETTER = 95;
  /** RegularExpression Id. */
  int DIGIT = 96;
  /** RegularExpression Id. */
  int SPECIALCHAR = 97;
  /** RegularExpression Id. */
  int FSSPECIALCHAR = 98;
  /** RegularExpression Id. */
  int FLOAT = 99;
  /** RegularExpression Id. */
  int INTEGER = 100;
  /** RegularExpression Id. */
  int NUMBER = 101;
  /** RegularExpression Id. */
  int IDENTIFIER = 102;
  /** RegularExpression Id. */
  int PATH = 103;
  /** RegularExpression Id. */
  int QUOTEDSTRING = 104;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int PIG_START = 1;
  /** Lexical state. */
  int SINGLE_LINE_COMMENT = 2;
  /** Lexical state. */
  int MULTI_LINE_COMMENT = 3;
  /** Lexical state. */
  int IN_STRING = 4;
  /** Lexical state. */
  int IN_COMMAND = 5;
  /** Lexical state. */
  int GENERATE = 6;
  /** Lexical state. */
  int SCHEMA_DEFINITION = 7;
  /** Lexical state. */
  int BAG_CONSTANT = 8;
  /** Lexical state. */
  int IN_BLOCK = 9;
  /** Lexical state. */
  int PIG_END = 10;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "<token of kind 5>",
    "\"cat\"",
    "\"cd\"",
    "\"cp\"",
    "\"copyFromLocal\"",
    "\"copyToLocal\"",
    "\"dump\"",
    "\"describe\"",
    "\"aliases\"",
    "\"explain\"",
    "\"help\"",
    "\"kill\"",
    "\"ls\"",
    "\"mv\"",
    "\"mkdir\"",
    "\"pwd\"",
    "\"quit\"",
    "\"register\"",
    "\"rm\"",
    "\"rmf\"",
    "\"set\"",
    "\"illustrate\"",
    "\"run\"",
    "\"exec\"",
    "\"-param\"",
    "\"-param_file\"",
    "\"-script\"",
    "\"-dot\"",
    "\"-out\"",
    "\"-brief\"",
    "\"scriptDone\"",
    "\"split\"",
    "\"define\"",
    "\"store\"",
    "<token of kind 39>",
    "\"\\\'\"",
    "\"`\"",
    "<token of kind 42>",
    "<token of kind 43>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"--\"",
    "\"/*\"",
    "<token of kind 49>",
    "<token of kind 50>",
    "<token of kind 51>",
    "<token of kind 52>",
    "\"*/\"",
    "<token of kind 54>",
    "<token of kind 55>",
    "\"\\\\\\\'\"",
    "\"\\\'\"",
    "<token of kind 58>",
    "<token of kind 59>",
    "\"\\\\`\"",
    "\"`\"",
    "<token of kind 62>",
    "<token of kind 63>",
    "\"{\"",
    "<token of kind 65>",
    "\";\"",
    "<token of kind 67>",
    "<token of kind 68>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 73>",
    "<token of kind 74>",
    "<token of kind 75>",
    "\"{\"",
    "\"}\"",
    "<token of kind 78>",
    "<token of kind 79>",
    "\"\\\"\"",
    "<token of kind 81>",
    "<token of kind 82>",
    "\"{\"",
    "<token of kind 84>",
    "\"\\\'\"",
    "\"`\"",
    "\"--\"",
    "\"/*\"",
    "<token of kind 89>",
    "<token of kind 90>",
    "\"\"",
    "<EOL>",
    "\"\\\'\"",
    "\";\"",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIALCHAR>",
    "<FSSPECIALCHAR>",
    "<FLOAT>",
    "<INTEGER>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<PATH>",
    "<QUOTEDSTRING>",
  };

}
