/* Generated By:JavaCC: Do not edit this line. DOTParserTreeConstants.java Version 4.2 */
package org.apache.pig.test.utils.dotGraph.parser;

public interface DOTParserTreeConstants
{
  public int JJTPARSE = 0;
  public int JJTATTRIBUTESTATEMENT = 1;
  public int JJTNODESTATEMENT = 2;
  public int JJTEDGESTATEMENT = 3;
  public int JJTATTRIBUTELIST = 4;
  public int JJTATTRIBUTE = 5;


  public String[] jjtNodeName = {
    "Parse",
    "AttributeStatement",
    "NodeStatement",
    "EdgeStatement",
    "AttributeList",
    "Attribute",
  };
}
/* JavaCC - OriginalChecksum=be70f5125604c4db675474338ff64575 (do not edit this line) */
