/* Generated By:JJTree&JavaCC: Do not edit this line. DOTParserConstants.java */
package org.apache.pig.test.utils.dotGraph.parser ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DOTParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 13;
  /** RegularExpression Id. */
  int RPAREN = 14;
  /** RegularExpression Id. */
  int LSQBRACKET = 15;
  /** RegularExpression Id. */
  int RSQBRACKET = 16;
  /** RegularExpression Id. */
  int EQUAL = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int DIRECTED_EDGE = 20;
  /** RegularExpression Id. */
  int EDGE = 21;
  /** RegularExpression Id. */
  int NODE = 22;
  /** RegularExpression Id. */
  int GRAPH = 23;
  /** RegularExpression Id. */
  int DIGRAPH = 24;
  /** RegularExpression Id. */
  int LETTER = 25;
  /** RegularExpression Id. */
  int DIGIT = 26;
  /** RegularExpression Id. */
  int SPECIAL_CHAR = 27;
  /** RegularExpression Id. */
  int NAME = 28;
  /** RegularExpression Id. */
  int QUOTEDSTRING = 29;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTI_COMMENT = 1;
  /** Lexical state. */
  int SINGLE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"//\"",
    "\"#\"",
    "\"/*\"",
    "<token of kind 8>",
    "\"*/\"",
    "<token of kind 10>",
    "<token of kind 11>",
    "<token of kind 12>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
    "\";\"",
    "\"->\"",
    "\"edge\"",
    "\"node\"",
    "\"graph\"",
    "\"digraph\"",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIAL_CHAR>",
    "<NAME>",
    "<QUOTEDSTRING>",
  };

}
